version: '3.3'
services:
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - eth0-selenium
  #selenium-chrome
  selenium-chrome:
    restart: always
    image: selenium/node-chrome-debug
    stdin_open: true
    links:
      - selenium-hub:hub
    networks:
      - eth0-selenium
  #selenium-firefox
  selenium-firefox:
    restart: always
    image: selenium/node-firefox-debug
    links:
      - selenium-hub:hub
    networks:
      - eth0-selenium
networks:
  eth0-selenium: